---
- name: Install build dependencies
  sudo: yes
  yum: name={{ item }} state=installed
  when: ansible_os_family == 'Ubuntu'
  with_items:
    - git
    - make
    - binutils
    - texinfo
    - gawk
    - sed
    - autoconf
    - build-essential
    - libpcre3-dev
    - g++

- include: node.yml
- include: node-cli-tools.yml

# ?
#* GCC 4.2 or newer
#* G++ 4.2 or newer
##* Python 2.6 or 2.7
#* GNU Make 3.81 or newer
#* libexecinfo (FreeBSD and OpenBSD only)