# Install Python 2.7 from sauce.

# wget http://python.org/ftp/python/2.7.5/Python-2.7.5.tgz
# http://askubuntu.com/questions/101591/how-do-i-install-python-2-7-2-on-ubuntu
#- include: python.yml # Python should be included already!

---
- name: Install build dependencies
  sudo: yes
  yum: name={{ item }} state=installed
  when: ansible_os_family == 'Ubuntu'
  with_items:
    - libreadline-gplv2-dev
    - libncursesw5-dev
    - libssl-dev
    - libsqlite3-dev
    - tk-dev
    - libgdbm-dev
    - libc6-dev
    - libbz2-dev

- name: Download Python
  sudo: no
  command: wget http://python.org/ftp/python/2.7.5/Python-2.7.5.tgz creates=/usr/local/bin/python

- name: Extract Python
  sudo: no
  command: tar -xzf Python-2.7.5.tgz creates=/usr/local/bin/python

- name: Configure Python
  sudo: no
  command: ./configure chdir=Python-2.7.5 creates=/usr/local/bin/python

- name: Make Python
  sudo: no
  command: make chdir=Python-2.7.5 creates=/usr/local/bin/python

- name: Install Python
  sudo: yes
  command: make install chdir=Python-2.7.5 creates=/usr/local/bin/python